\COPY dpe(
    dpe_number,
    dpe_reception_date,
    dpe_issue_date,
    inspector_visit_date,
    dpe_expiry_date,
    dpe_method,
    dpe_label,
    ghg_label,
    energy_use_kwhepm2year,
    ghg_emissions_kgco2m2year,
    construction_year,
    erp_category,
    construction_period,
    activity_sector,
    occupant_count,
    gross_floor_area,
    usable_area,
    main_heating_energy_type,
    city_name_ban,
    insee_code_ban,
    street_number_ban,
    ban_id,
    address_ban,
    postal_code_ban,
    ban_score,
    street_name_ban,
    x_coordinate_ban,
    y_coordinate_ban,
    apartment_floor,
    residence_name,
    building_address_details,
    housing_address_details,
    geocoding_status,
    department_number_ban,
    region_number_ban,
    final_energy_use_01,
    primary_energy_use_01,
    energy_type_01,
    energy_usage_type_01,
    annual_energy_cost_01,
    energy_reading_year_01,
    final_energy_use_02,
    primary_energy_use_02,
    energy_type_02,
    energy_usage_type_02,
    annual_energy_cost_02,
    energy_reading_year_02,
    final_energy_use_03,
    primary_energy_use_03,
    energy_type_03,
    energy_usage_type_03,
    annual_energy_cost_03,
    energy_reading_year_03
) FROM './data/ademe_english.csv'
WITH (
    FORMAT CSV,
    HEADER true,
    DELIMITER ',',
    NULL '',
    ENCODING 'UTF8'
);
